POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Cobol"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/*
